import { z } from "zod";

const noLineBreaks = (value: string) => !/[\r\n\u0000]/.test(value);
const noNullBytes = (value: string) => !value.includes("\u0000");

const singleLine = (minimum: number, maximum: number) =>
  z
    .string()
    .trim()
    .min(minimum)
    .max(maximum)
    .refine(noLineBreaks, "Use a single line.");

const sourcePage = z
  .string()
  .trim()
  .max(160)
  .refine((value) => value.startsWith("/") && !value.startsWith("//"), "Use a local page path.")
  .optional();

const turnstileToken = z.string().trim().min(1).max(8_192);

/**
 * Honeypot values are parsed but never persisted. A non-empty value receives
 * the same generic acknowledgement as a normal successful request.
 */
const honeypot = z.string().trim().max(0).optional();

export const contactSubmissionSchema = z
  .object({
    name: singleLine(2, 100),
    email: z.string().trim().email().max(254),
    subject: singleLine(3, 160),
    message: z
      .string()
      .trim()
      .min(10)
      .max(5_000)
      .refine(noNullBytes, "Message contains unsupported characters."),
    sourcePage,
    turnstileToken,
    website: honeypot,
  })
  .strict();

export type ContactSubmission = z.infer<typeof contactSubmissionSchema>;

export const newsletterSubmissionSchema = z
  .object({
    email: z.string().trim().email().max(254),
    sourcePage,
    turnstileToken,
    website: honeypot,
  })
  .strict();

export type NewsletterSubmission = z.infer<typeof newsletterSubmissionSchema>;

/**
 * Unsubscribe tokens are UUID bearer capabilities generated by PostgreSQL.
 * Keep this browser-safe validator shared by the fragment reader and server
 * handler so malformed values are never sent to the database.
 */
export const newsletterUnsubscribeTokenSchema = z.string().uuid();

export function isNewsletterUnsubscribeToken(value: unknown): value is string {
  return newsletterUnsubscribeTokenSchema.safeParse(value).success;
}

export function normalizePublicEmail(email: string): string {
  return email.trim().toLowerCase();
}
